# Generated by Django 4.2.1 on 2023-10-01 10:53

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, unique=True, verbose_name='Имя')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nom', unique=True)),
                ('numero', models.CharField(blank=True, max_length=250, verbose_name='Телефон')),
                ('ville', models.CharField(blank=True, max_length=250, verbose_name='Город')),
                ('adresse', models.CharField(blank=True, max_length=250, verbose_name='Адрес')),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=250, unique=True, verbose_name="Today's date")),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='date', unique=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recu', models.CharField(max_length=250, unique=True, verbose_name='Накладная')),
                ('action', models.CharField(choices=[('Долг', 'Долг'), ('Оплатить Долг', 'Оплатить Долг')], default=1, max_length=250, verbose_name='Действия')),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма ($)')),
                ('client', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.client', verbose_name='Покупатель')),
                ('date', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.date', verbose_name='дата')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
