# Generated by Django 4.2.1 on 2023-10-04 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='action',
            field=models.CharField(choices=[('Долг', 'Долг')], default=1, max_length=250, verbose_name='Действия'),
        ),
        migrations.CreateModel(
            name='PaiementsCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recu', models.CharField(max_length=250, unique=True, verbose_name='Накладная')),
                ('action', models.CharField(choices=[('Оплатить Долг', 'Оплатить Долг')], default=1, max_length=250, verbose_name='Действия')),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма ($)')),
                ('client', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.client', verbose_name='Покупатель')),
                ('date', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.date', verbose_name='дата')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
