# Generated by Django 4.2.1 on 2023-10-26 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_titulairecarte_alter_client_numero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementCarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recu', models.CharField(max_length=250, verbose_name='Накладная')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Сумма ($)')),
                ('action', models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], default=1, max_length=250, verbose_name='Оплата')),
                ('carte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.titulairecarte', verbose_name='Карта')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.client', verbose_name='Покупатель')),
                ('date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.date', verbose_name='дата')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.DeleteModel(
            name='Carte',
        ),
    ]
