# Generated by Django 4.2.1 on 2023-12-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_paiementcarte_delete_carte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.CharField(default='01-01-2024', max_length=250, unique=True, verbose_name='Сегодняшняя дата'),
        ),
    ]
